### ISSUE TITLE
release(payload, priority, delay) does not parse priority/delay properly

### ISSUE THREAD

**Issue by MarkBlah** [getjackd/jackd#30] opened 2023-03-19 09:10 UTC
https://github.com/getjackd/jackd/blob/dd02660a07f76ead72f334c18fe46ca7fa00a60b/dist/index.js#L73

priority/delay defaults to 0

**Comment by divmgl** [comment] 2023-09-11 05:06
Hi! I'm not understanding this issue unfortunately! If a priority and/or a delay is not supplied, they both default to 0. Is there a different functionality you're expecting here? Or maybe an error you're having? 

I'm gonna go ahead and close this ticket because this seems to be working as intended. If you have any additional information I'd be happy to look into it!

**Closed by divmgl** 2023-09-11 05:06 UTC
